# Generated by Django 3.2.5 on 2021-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210801_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_contrat',
            field=models.CharField(choices=[('partiel', 'partiel'), ('plein', 'plein'), ('stage', 'stage')], default='plein', max_length=20),
        ),
    ]
