# Generated by Django 3.2.5 on 2021-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_job_company_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_salary',
            field=models.CharField(choices=[('moins_de_5oo', 'moins_de_5oo'), ('500-1000', '500-1000'), ('1000-1500', '1000-1500'), ('2000-2500', '2000-2500'), ('2500-3000', '2500-3000'), ('3000+', '3000+')], default='500-1000', max_length=20),
        ),
    ]
